[project]
name = "swe-agent-server"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["pydantic", "requests", "backoff", "aiohttp", "awscli", "openhands-sdk==1.37.1", "openhands-tools==1.37.1", "aws-opentelemetry-distro"]

[project.optional-dependencies]
strands = ["strands-agents[litellm]==1.50.2", "strands-agents-tools"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"*" = ["*.json", "*.yaml", "*.yml", "*.toml", "*.txt", "*.md", "*.jinja", "*.j2"]
