actor_rollout_ref:
  actor:
    strategy: megatron
    megatron:
      use_mbridge: true
      vanilla_mbridge: false
      use_dist_checkpointing: false

      override_transformer_config:
        # LoRA without NVIDIA Apex requires the fused path off
        gradient_accumulation_fusion: false
